const ORDER_STATUS = {
  PLACED: 'PLACED',
  PROCESSING: 'PROCESSING',
  READY_TO_SHIP: 'READY_TO_SHIP',
};

const PAYMENT_STATUS = {
  PAID: 'PAID',
  PENDING: 'PENDING',
};

const SCHEDULER_INTERVALS = {
  PLACED_TO_PROCESSING: 10 * 60 * 1000,
  PROCESSING_TO_READY: 20 * 60 * 1000,
};

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

module.exports = {
  ORDER_STATUS,
  PAYMENT_STATUS,
  SCHEDULER_INTERVALS,
  PAGINATION,
};
